### ISSUE TITLE
WORKER TIMEOUT Error

### ISSUE THREAD

**Issue by peddollakishore** [pratos/flask_api#1]
Hi @pratos 
When i am running the procedure i am getting below error, please have a look screenshots. 

![screenshot from 2017-09-29 03-30-03](https://user-images.githubusercontent.com/16456445/31012505-e85ef49c-a4c6-11e7-97bf-3d20064dc02f.png)
![screenshot from 2017-09-29 03-30-36](https://user-images.githubusercontent.com/16456445/31012517-f4d7f1ce-a4c6-11e7-87f2-19959a07f853.png)

thanks in advance.

**Comment by pratos** [comment]
Can you try out: 
    * pip install --upgrade gunicorn`
    * `gunicorn --reload -w 2 --bind 0.0.0.0:8000 hello-world:app`

This is an absolutely weird error, never got it. But assuming you have more than 2 cores, `-w 2` would create 2 workers and `--reload` wil reload if it fails. 

If it solves the problem, do mark the issue as resolved and close it :smile:

**Comment by peddollakishore** [comment]
Thanks for reply @pratos ,

sorry still i am facing same issue.

![screenshot from 2017-09-29 04-57-07](https://user-images.githubusercontent.com/16456445/31015037-cd662d20-a4d2-11e7-8d59-bdb5ee8ff07e.png)
![screenshot from 2017-09-29 04-57-22](https://user-images.githubusercontent.com/16456445/31015040-d0ec54a6-a4d2-11e7-9e4f-ee1f56a45c17.png)
please help me out of this..

**Comment by pratos** [comment]
Okay, leave `gunicorn` for this bit.

You need to add a small bit to `hello-world.py`:

```hello-world.py
from flask import Flask

app = Flask(__name__)

@app.route('/users/<string:username>')
def hello_world(username=None):
    return("Hello {}!".format(username))

if __name__ == "__main__":
    app.run(port=8000)
```

- Then go to the terminal, run: `python hello-world.py`

This should definitely work. So `Flask` has its inbuilt HTTP server that we can use, `gunicorn` and `uwsgi` are alternative HTTP Server.

**Comment by pratos** [comment]
Closing the issue on account of non-response, the above resolution will work for sure. If not please reopen again.
